name: expense
networks:
  default:
    name: expense
volumes:
  mysql:
    external: true  #if true, you need to create volume manually --> docker volume create mysql
services:
  mysql:
    image: mysql:v1.0     ## before run the docker compose file, docker image should be available
    container_name: mysql   ## --name mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ExpenseApp@1
      - MYSQL_USER=expense
      - MYSQL_PASSWORD=ExpenseApp@1
      - MYSQL_DATABASE=transactions
# it is good to provide the secrets at runtime like promting or commandline agrs.. but for time being we hard coded here.
    volumes:
      - source: mysql
        target: /var/lib/mysql    ## mysql home directory
        type: volume    # -v volume-name:/path/in/container
  backend:
    image: backend:v1.0
    container_name: backend
    command: sh -c "sleep 20 && node /opt/server/index.js"
    depends_on:
      - mysql
  frontend:
    image: frontend:v1.0
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"